#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for dmos_user
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {
    'metadata_version': '1.1',
    'status': ['preview'],
    'supported_by': '<support_group>'
}

DOCUMENTATION = """
---
module: dmos_user
version_added: 2.9
short_description: 'Manages <xxxx> attributes of <network_os> <resource>.'
description: 'Manages <xxxx> attributes of <network_os> <resource>'
author: Ansible Network Engineer
notes:
  - 'Tested against <network_os> <version>'
options:
  config:
    description: The DMOS user configuration
    type: list
    elements: dict
    suboptions:
      name:
        type: str
      alias:
        type: list
        elements: dict
        suboptions:
          name:
            type: str
          expansion:
            type: str
      description:
        type: str
      session:
        type: dict
        suboptions:
          complete_on_space:
            description: Enable/disable completion on space
            type: bool
          devtools:
            description: Enable/disable development tools
            type: bool
          display_level:
            description: Max depth to show when displaying configuration
            type: int
          history:
            description: History size
            type: int
          idle_timeout:
            description: CLI idle-timeout in seconds
            type: int
          ignore_leading_space:
            description: Ignore leading whitespace
            type: bool
          paginate:
            description: Paginate output from CLI commands
            type: bool
          show_defaults:
            description: Show default values when showing the configuration
            type: bool
  state:
    description:
    - The state the configuration should be left in
    type: str
    choices:
    - merged
    - replaced
    - overridden
    - deleted
    default: merged
"""
EXAMPLES = """
"""
RETURN = """
before:
  description: The configuration prior to the model invocation.
  returned: always
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
after:
  description: The resulting configuration model invocation.
  returned: when changed
  sample: >
    The configuration returned will always be in the same format
     of the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.network.dmos.argspec.user.user import UserArgs
from ansible.module_utils.network.dmos.config.user.user import User


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=UserArgs.argument_spec,
                           supports_check_mode=True)

    result = User(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
